### ISSUE TITLE
762x39 and 762x51 are flipped

### ISSUE THREAD

**Issue by Joshj5hawk** [Joshj5hawk/JoshJ5Hawk-SuperAmmo#1]

**Comment by Joshj5hawk** [comment]
Fixed in 2.0.1

**Comment by Snowblind808** [comment]
might just be me, cuz i did the mods wrong or something, but i downloaded 2.0.1 and it still shows them flipped, but the image that you see when its in your stash, the actual look of the cartage in magazines and in the inspect looks correct, so only a small issue even then, just thought id at least bring it up

**Comment by Joshj5hawk** [comment]
> might just be me, cuz i did the mods wrong or something, but i downloaded 2.0.1 and it still shows them flipped, but the image that you see when its in your stash, the actual look of the cartage in magazines and in the inspect looks correct, so only a small issue even then, just thought id at least bring it up

Oh that should be a simple fix! When you open you launcher, click settings in the top right, and clear temp files. That should reload all the images and show them properly!

**Comment by Snowblind808** [comment]
thanks, it did fix the problem
