### ISSUE TITLE
Super ammo's dont work with revolvers

### ISSUE THREAD

**Issue by Snowblind808** [Joshj5hawk/JoshJ5Hawk-SuperAmmo#3]
The MTs-225 aka revolver shotgun, the 9x19 and .357 pistol revolvers, and the revolving grenade launcher dont work, as well as the double barrel shotgun only being able to take one round of the super 12 gauge

i know this is already know, just putting it formally here for them

**Comment by Joshj5hawk** [comment]
Fixed! I hope lol

**Comment by Snowblind808** [comment]
all of the shotguns are correct, the double barrel and the revolver shotgun are working correctly, as well as the .357 revolver, but the 9x19 revolver and the revolving grenade launcher are still not working, sorry

**Comment by Joshj5hawk** [comment]
Not your fault, thanks for pointing it out!

**Comment by Joshj5hawk** [comment]
> 

Are you sure the 9x19 doesn't work? I just tried it and it seemed okay on my end? If not, try grabbing version 3.0.4

**Comment by Snowblind808** [comment]
yea, 9x19 strangely still dosent work for me, and i dont know why that is, i even tried the new version, it still dosent work

**Comment by Snowblind808** [comment]
i know why the 9x19 isnt working, you have a seperate 9x19 ammo that looks like the ammo for the mp7 but its named 9x19, the ammo that goes in the revolver is 9x19PARA, not the 9x19 that looks like the mp7 ammo, you should remove that one and fix the ammo that dosent work with it

**Comment by Snowblind808** [comment]
can confirm, all revolvers now work
